# Generated by Django 5.1.3 on 2024-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_finish_date_roster_job_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='in_service',
            field=models.BooleanField(default=False),
        ),
    ]
