# Generated by Django 5.1.3 on 2024-11-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vehicle_in_service'),
    ]

    operations = [
    ]
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vehicle_in_service'),  # Replace with your latest migration file name
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE myapp_roster DROP COLUMN driver_status;",  # Drop the column
            reverse_sql="ALTER TABLE myapp_roster ADD COLUMN driver_status VARCHAR(50) NOT NULL DEFAULT 'Available';"  # Reverse operation
        ),
    ]
