# Generated by Django 5.1.3 on 2024-11-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20241121_0910'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE myapp_roster DROP COLUMN runsheet_received;",
            reverse_sql="ALTER TABLE myapp_roster ADD COLUMN runsheet_received BOOLEAN;"
        ),
    ]
